import React from "react";
import Sidebar from "./components/sidebar";
import Navbar from "./components/navbar";
import { Metadata } from "next";
import { navLinks } from "./constants";

export const metadata: Metadata = {
  title: "Administration",
  description: "Generated by create next app",
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className="xl:grid xl:grid-cols-12">
      <Sidebar navLinks={navLinks} />
      <div className="flex flex-col w-full overflow-clip xl:col-span-10">
        <Navbar navLinks={navLinks} />
        <div className="xl:px-14 lg:px-8 px-4 mb-9 mt-4">{children}</div>
      </div>
    </main>
  );
}
